#!/usr/bin/env node
"use strict";

/**
 * Generates docker-compose.yml for the Phala CVM.
 *
 * The engine's code ships INSIDE the compose file (base64, written to /app at
 * container start) on top of an already-published base image that only
 * supplies node_modules. Consequences worth knowing:
 *  - No new image has to be pushed anywhere: only the base image digest below
 *    (pulled, never published) is fetched from a registry.
 *  - Phala's RTMR3 covers the whole compose file, so the exact index.js and
 *    matcher.js are part of what the attestation quote measures -- stronger
 *    than an opaque image tag. The sha256 of each file is also written as a
 *    comment so a reader can check the embedded code against the repo.
 *  - Dependencies must stay identical to the base image's package.json.
 *
 * Two modes:
 *  - `node make-compose.js`                     embedded code (above)
 *  - `node make-compose.js --image sha256:<d>`  plain compose that runs an image
 *    you pushed yourself (`docker buildx build --push ...`), pinned by digest.
 *    Verify the image holds the repo's sources first:
 *    `docker run --rm --entrypoint sh <image>@<d> -c "sha256sum /app/*.js"`.
 *
 * Then `npx phala deploy --cvm-id <id> -c docker-compose.yml`.
 */

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

// Published earlier (dependencies only matter here); pinned by digest.
const BASE_IMAGE =
  "ynsmlkc/attest-matching-engine@sha256:1d52d7a710b2fec3fb8f8f8d597fdc2ffb03ae32939c634cfd214c768a49d3b7";
const FILES = ["index.js", "matcher.js"];

const imageArg = process.argv.indexOf("--image");
const IMAGE_DIGEST = imageArg > -1 ? process.argv[imageArg + 1] : null;
if (IMAGE_DIGEST && !/^sha256:[0-9a-f]{64}$/.test(IMAGE_DIGEST)) {
  console.error("--image needs a digest like sha256:<64 hex>");
  process.exit(1);
}

const parts = FILES.map((name) => {
  const buf = fs.readFileSync(path.join(__dirname, name));
  return {
    name,
    sha256: crypto.createHash("sha256").update(buf).digest("hex"),
    b64: buf.toString("base64"),
  };
});

const write = parts.map((p) => `echo '${p.b64}' | base64 -d > /app/${p.name}`).join(" && ");
const shaComments = parts.map((p) => `# ${p.name} sha256: ${p.sha256}`).join("\n");

const ENV_BLOCK = `    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
    ports:
      - "80:80"
    environment:
      # SETTLEMENT_VAULT_ID / ENCLAVE_ID_HEX are deliberately NOT here — they
      # are set after boot via POST /configure so changing which vault this
      # engine talks to never changes RTMR3.
      - SOROBAN_RPC_URL=https://soroban-testnet.stellar.org
      - NETWORK_PASSPHRASE=Test SDF Network ; September 2015
      - ENGINE_KEY_PATH=attest/matching-engine/v1
      # The value comes from a sealed env var (\`phala envs update\`), never
      # written in plaintext in this file.
      - ADMIN_KEY=\${ADMIN_KEY}
    restart: always
`;

const compose = IMAGE_DIGEST
  ? `# GENERATED by make-compose.js --image -- edit the sources, rebuild + push the
# image, then regenerate. Deployed to Phala Cloud as a real TDX CVM. Mounts
# dstack's guest-agent socket so the service can derive its own Stellar keypair.
${shaComments}
services:
  matching-engine:
    # Pinned to a digest, not a tag: RTMR3 covers this file, so the exact image
    # is what gets attested. The image holds the files whose sha256 are listed
    # above (checked before deploying).
    image: ynsmlkc/attest-matching-engine@${IMAGE_DIGEST}
${ENV_BLOCK}`
  : `# GENERATED by make-compose.js -- edit index.js / matcher.js, then regenerate.
# Deployed to Phala Cloud as a real TDX CVM. Mounts dstack's guest-agent socket
# so the service can derive its own Stellar keypair (DstackClient.getKey).
#
# The engine's code is embedded below (base64) rather than baked into a new
# image, so it is covered by RTMR3 and no new image needs publishing. See
# make-compose.js for the reasoning.
${shaComments}
services:
  matching-engine:
    # Base image: dependencies only, pinned by digest (its own index.js is
    # overwritten at start).
    image: ${BASE_IMAGE}
    entrypoint:
      - sh
      - -c
      - "${write} && exec node /app/index.js"
${ENV_BLOCK}`;

fs.writeFileSync(path.join(__dirname, "docker-compose.yml"), compose);
console.log(`docker-compose.yml written (${compose.length} bytes)`);
for (const p of parts) console.log(`  ${p.name} sha256 ${p.sha256}`);
